config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'reviews#index'

  resources :reviews, only: [:index, :new, :create, :show]

  resources :users, only: [:show]
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :video, presence: true

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << [:username]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user = current_user

    if @review.save
      flash[:notice] = "Review created!"
      redirect_to reviews_path(@reviews)
    else
      render :new
    end
  end

  def show
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:title, :description, :video, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

  <nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Mobile Madness", root_path %></h1>
    </li>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if !user_signed_in? %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% else %>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
      <li><%= link_to current_user.username, user_path(current_user) %></li>
      <% end %>
      <li><%= link_to "Post a review!", new_review_path %>
        </ul>
      </li>
    </ul>
  </section>
</nav>

  <div><p class="notice"><%= notice %></p></div>
  <div><p class="alert"><%= alert %></p></div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/reviews/index.html.erb
<h1>Reviews Index</h1>


<% @reviews.each do |review|%>
  <div><%= image_tag review.image %></div>
  <div><%= link_to review.title, review_path(review) %><div>
<% end %>

app/views/reviews/new.html.erb
<h1>Submit a Review</h1>

<% if @review.errors.any? %>
  <h2>Error!</h2>
  <ul>
  <% @review.errors.full_messages.each do |error_msg| %>
    <li><%= error_msg %></li>
  <% end %>
  </ul>
<% end %>

<%= form_for @review do |f| %>
  <%= f.label :image %><br />
  <%= f.file_field :image %>

  <%= f.label :title %>
  <%= f.text_field :title %> <br/>

  <%= f.label :description %>
  <%= f.text_field :description %> <br/>

  <%= f.label :video %>
  <%= f.text_field :video %> <br/>

  <%= f.submit "Submit Review" %> <br/>
<%end%>

app/views/reviews/show.html.erb
<br/>
<br/>
<li><%= @review.title %></li>
<li><%= @review.description %></li>
<iframe width="560" height="315" src=<%= "#{@review.video.gsub(/^(https:)/,"").gsub('watch?v=', "embed/")}" %> frameborder="0" allowfullscreen</iframe>

app/views/users/show.html.erb
<div>
  <% if current_user %>
  <%= link_to 'Edit Profile', edit_user_registration_path(@user) %>
  <% end %>
</div>
<div>Username: <%= @user.username %></div>